---

# # bareos_dir_messages: Daemon

argument_specs:
  main:
    short_description: "Install and configure BareOS File Daemon on your system."
    description: >
      Install and configure BareOS File Daemon on your system.
    author: Robert de Bock
    options:
      bareos_fd_backup_configurations:
        type: "bool"
        default: no
        description: "Backup existing configurations."
      bareos_fd_hostname:
        type: "str"
        default: "{{ inventory_hostname }}"
        description: "The hostname of the File Daemon."
      bareos_fd_max_job_bandwidth:
        type: "str"
        default: "10 mb/s"
        description: "The maximum bandwidth to use."
      bareos_fd_message:
        type: "str"
        default: "Standard"
        description: "The message to use."
      bareos_fd_tls_enable:
        type: "bool"
        default: yes
        description: "Enable TLS."
      bareos_fd_tls_verify_peer:
        type: "bool"
        default: no
        description: "Verify the peer."
      bareos_fd_heartbeat_interval:
        type: "int"
        default: 0
        description: "The inteval in seconds to send a heartbeat."
      bareos_fd_directors:
        type: "list"
        default: []
        description: "The Directors to connect to."
      bareos_fd_messages:
        type: "list"
        default: []
        description: "The Messages to configure."
