---

- name: assert | Test if bareos_backup_configurations is set correctly
  ansible.builtin.assert:
    that:
      - bareos_fd_backup_configurations is defined
      - bareos_fd_backup_configurations is boolean
    quiet: yes

- name: assert | Test if bareos_fd_hostname is set correctly
  ansible.builtin.assert:
    that:
      - bareos_fd_hostname is defined
      - bareos_fd_hostname is string
      - bareos_fd_hostname is not none
    quiet: yes

- name: assert | Test if bareos_fd_max_job_bandwidth is set correctly
  ansible.builtin.assert:
    that:
      - bareos_fd_max_job_bandwidth is defined
      - bareos_fd_max_job_bandwidth is string
      - bareos_fd_max_job_bandwidth is not none
    quiet: yes

- name: assert | Test if bareos_fd_message is set correctly
  ansible.builtin.assert:
    that:
      - bareos_fd_message is defined
      - bareos_fd_message is string
      - bareos_fd_message is not none
    quiet: yes

- name: assert | Test if bareos_fd_tls_enable is set correctly
  ansible.builtin.assert:
    that:
      - bareos_fd_tls_enable is defined
      - bareos_fd_tls_enable is boolean
    quiet: yes

- name: assert | Test if bareos_fd_tls_verify_peer is set correctly
  ansible.builtin.assert:
    that:
      - bareos_fd_tls_verify_peer is defined
      - bareos_fd_tls_verify_peer is boolean
    quiet: yes

- name: assert | Test if bareos_fd_heartbeat_interval is set correctly
  ansible.builtin.assert:
    that:
      - bareos_fd_heartbeat_interval is defined
      - bareos_fd_heartbeat_interval is number
    quiet: yes

- name: assert | Test if bareos_fd_directors is set correctly
  ansible.builtin.assert:
    that:
      - bareos_fd_directors is defined
      - bareos_fd_directors is iterable
    quiet: yes

- name: assert | Test if bareos_fd_messages is set correctly
  ansible.builtin.assert:
    that:
      - bareos_fd_messages is defined
      - bareos_fd_messages is iterable
    quiet: yes
